// Comprehensive Country and City data
export interface Country {
  value: string
  label: string
  cities: City[]
  code: string // ISO country code
}

export interface City {
  value: string
  label: string
}

// Comprehensive list of countries with their major cities
// Countries are listed alphabetically and sorted by getCountryOptions()
export const countries: Country[] = [
  // A
  {
    value: 'af',
    label: 'Afghanistan',
    code: 'AF',
    cities: [
      { value: 'kabul', label: 'Kabul' },
      { value: 'kandahar', label: 'Kandahar' },
      { value: 'herat', label: 'Herat' },
      { value: 'mazar-i-sharif', label: 'Mazar-i-Sharif' },
      { value: 'jalalabad', label: 'Jalalabad' },
      { value: 'kunduz', label: 'Kunduz' },
      { value: 'ghazni', label: 'Ghazni' },
      { value: 'balkh', label: 'Balkh' },
      { value: 'khost', label: 'Khost' },
      { value: 'baghlan', label: 'Baghlan' },
      { value: 'gardez', label: 'Gardez' },
      { value: 'jowzjan', label: 'Jowzjan' },
      { value: 'lashkar-gah', label: 'Lashkar Gah' },
      { value: 'taloqan', label: 'Taloqan' },
      { value: 'pul-e-khumri', label: 'Pul-e-Khumri' },
      { value: 'charikar', label: 'Charikar' },
      { value: 'sar-e-pol', label: 'Sar-e-Pol' },
      { value: 'kunar', label: 'Kunar' },
      { value: 'shibirghan', label: 'Shibirghan' },
      { value: 'ghor', label: 'Ghor' },
      { value: 'faryab', label: 'Faryab' },
      { value: 'logar', label: 'Logar' },
      { value: 'zaranj', label: 'Zaranj' },
      { value: 'kandahar-province', label: 'Kandahar Province' },
    ],
  },
  {
    value: 'al',
    label: 'Albania',
    code: 'AL',
    cities: [
      { value: 'tirana', label: 'Tirana' },
      { value: 'durres', label: 'Durrës' },
      { value: 'vlore', label: 'Vlorë' },
      { value: 'shkoder', label: 'Shkodër' },
      { value: 'fier', label: 'Fier' },
      { value: 'korce', label: 'Korçë' },
      { value: 'elbasan', label: 'Elbasan' },
      { value: 'berat', label: 'Berat' },
    ],
  },
  {
    value: 'dz',
    label: 'Algeria',
    code: 'DZ',
    cities: [
      { value: 'algiers', label: 'Algiers' },
      { value: 'oran', label: 'Oran' },
      { value: 'constantine', label: 'Constantine' },
      { value: 'annaba', label: 'Annaba' },
      { value: 'blida', label: 'Blida' },
      { value: 'batna', label: 'Batna' },
      { value: 'djelfa', label: 'Djelfa' },
      { value: 'setif', label: 'Sétif' },
    ],
  },
  { value: 'ad', label: 'Andorra', code: 'AD', cities: [] },
  { value: 'ao', label: 'Angola', code: 'AO', cities: [] },
  { value: 'ag', label: 'Antigua and Barbuda', code: 'AG', cities: [] },
  {
    value: 'ar',
    label: 'Argentina',
    code: 'AR',
    cities: [
      { value: 'buenos-aires', label: 'Buenos Aires' },
      { value: 'cordoba', label: 'Córdoba' },
      { value: 'rosario', label: 'Rosario' },
      { value: 'mendoza', label: 'Mendoza' },
      { value: 'tucuman', label: 'Tucumán' },
      { value: 'la-plata', label: 'La Plata' },
      { value: 'mar-del-plata', label: 'Mar del Plata' },
      { value: 'salta', label: 'Salta' },
      { value: 'santa-fe', label: 'Santa Fe' },
      { value: 'san-juan', label: 'San Juan' },
      { value: 'resistance', label: 'Resistencia' },
      { value: 'santiago-del-estero', label: 'Santiago del Estero' },
      { value: 'corrientes', label: 'Corrientes' },
      { value: 'posadas', label: 'Posadas' },
      { value: 'formosa', label: 'Formosa' },
      { value: 'neuquen', label: 'Neuquén' },
      { value: 'bahia-blanca', label: 'Bahía Blanca' },
      { value: 'san-salvador-de-jujuy', label: 'San Salvador de Jujuy' },
      { value: 'parana', label: 'Paraná' },
      { value: 'merlo', label: 'Merlo' },
      { value: 'godoy-cruz', label: 'Godoy Cruz' },
      { value: 'rio-cuarto', label: 'Río Cuarto' },
      { value: 'comodoro-rivadavia', label: 'Comodoro Rivadavia' },
      { value: 'san-luis', label: 'San Luis' },
      { value: 'san-rafael', label: 'San Rafael' },
    ],
  },
  { value: 'am', label: 'Armenia', code: 'AM', cities: [] },
  {
    value: 'au',
    label: 'Australia',
    code: 'AU',
    cities: [
      { value: 'sydney', label: 'Sydney' },
      { value: 'melbourne', label: 'Melbourne' },
      { value: 'brisbane', label: 'Brisbane' },
      { value: 'perth', label: 'Perth' },
      { value: 'adelaide', label: 'Adelaide' },
      { value: 'gold-coast', label: 'Gold Coast' },
      { value: 'newcastle', label: 'Newcastle' },
      { value: 'canberra', label: 'Canberra' },
      { value: 'sunshine-coast', label: 'Sunshine Coast' },
      { value: 'wollongong', label: 'Wollongong' },
      { value: 'geelong', label: 'Geelong' },
      { value: 'hobart', label: 'Hobart' },
      { value: 'townsville', label: 'Townsville' },
      { value: 'cairns', label: 'Cairns' },
      { value: 'darwin', label: 'Darwin' },
      { value: 'toowoomba', label: 'Toowoomba' },
      { value: 'ballarat', label: 'Ballarat' },
      { value: 'bendigo', label: 'Bendigo' },
      { value: 'albury', label: 'Albury' },
      { value: 'launceston', label: 'Launceston' },
      { value: 'mackay', label: 'Mackay' },
      { value: 'rockhampton', label: 'Rockhampton' },
      { value: 'bunbury', label: 'Bunbury' },
      { value: 'bundaberg', label: 'Bundaberg' },
      { value: 'coffs-harbour', label: 'Coffs Harbour' },
      { value: 'wagga-wagga', label: 'Wagga Wagga' },
      { value: 'hervey-bay', label: 'Hervey Bay' },
      { value: 'port-macquarie', label: 'Port Macquarie' },
      { value: 'mildura', label: 'Mildura' },
      { value: 'tamworth', label: 'Tamworth' },
      { value: 'traralgon', label: 'Traralgon' },
      { value: 'orange', label: 'Orange' },
      { value: 'shepparton', label: 'Shepparton' },
      { value: 'dubbo', label: 'Dubbo' },
      { value: 'geraldton', label: 'Geraldton' },
      { value: 'nowra', label: 'Nowra' },
      { value: 'bathurst', label: 'Bathurst' },
      { value: 'warrnambool', label: 'Warrnambool' },
      { value: 'albany', label: 'Albany' },
      { value: 'devonport', label: 'Devonport' },
      { value: 'kalgoorlie', label: 'Kalgoorlie' },
      { value: 'mount-gambier', label: 'Mount Gambier' },
      { value: 'lismore', label: 'Lismore' },
      { value: 'whyalla', label: 'Whyalla' },
      { value: 'burnie', label: 'Burnie' },
      { value: 'broome', label: 'Broome' },
      { value: 'port-augusta', label: 'Port Augusta' },
      { value: 'port-lincoln', label: 'Port Lincoln' },
      { value: 'gladstone', label: 'Gladstone' },
      { value: 'maryborough', label: 'Maryborough' },
      { value: 'mount-isa', label: 'Mount Isa' },
      { value: 'alice-springs', label: 'Alice Springs' },
      { value: 'karratha', label: 'Karratha' },
      { value: 'port-hedland', label: 'Port Hedland' },
      { value: 'newman', label: 'Newman' },
      { value: 'esperance', label: 'Esperance' },
      { value: 'ceduna', label: 'Ceduna' },
      { value: 'coober-pedy', label: 'Coober Pedy' },
      { value: 'uluru', label: 'Uluru' },
    ],
  },
  { value: 'at', label: 'Austria', code: 'AT', cities: [] },
  { value: 'az', label: 'Azerbaijan', code: 'AZ', cities: [] },
  
  // B
  { value: 'bs', label: 'Bahamas', code: 'BS', cities: [] },
  { value: 'bh', label: 'Bahrain', code: 'BH', cities: [] },
  {
    value: 'bd',
    label: 'Bangladesh',
    code: 'BD',
    cities: [
      { value: 'dhaka', label: 'Dhaka' },
      { value: 'chittagong', label: 'Chittagong' },
      { value: 'khulna', label: 'Khulna' },
      { value: 'rajshahi', label: 'Rajshahi' },
      { value: 'sylhet', label: 'Sylhet' },
      { value: 'barisal', label: 'Barisal' },
      { value: 'comilla', label: 'Comilla' },
      { value: 'mymensingh', label: 'Mymensingh' },
    ],
  },
  { value: 'bb', label: 'Barbados', code: 'BB', cities: [] },
  { value: 'by', label: 'Belarus', code: 'BY', cities: [] },
  { value: 'be', label: 'Belgium', code: 'BE', cities: [] },
  { value: 'bz', label: 'Belize', code: 'BZ', cities: [] },
  { value: 'bj', label: 'Benin', code: 'BJ', cities: [] },
  { value: 'bt', label: 'Bhutan', code: 'BT', cities: [] },
  { value: 'bo', label: 'Bolivia', code: 'BO', cities: [] },
  { value: 'ba', label: 'Bosnia and Herzegovina', code: 'BA', cities: [] },
  { value: 'bw', label: 'Botswana', code: 'BW', cities: [] },
  {
    value: 'br',
    label: 'Brazil',
    code: 'BR',
    cities: [
      { value: 'sao-paulo', label: 'São Paulo' },
      { value: 'rio-de-janeiro', label: 'Rio de Janeiro' },
      { value: 'brasilia', label: 'Brasília' },
      { value: 'salvador', label: 'Salvador' },
      { value: 'fortaleza', label: 'Fortaleza' },
      { value: 'belo-horizonte', label: 'Belo Horizonte' },
      { value: 'manaus', label: 'Manaus' },
      { value: 'curitiba', label: 'Curitiba' },
      { value: 'recife', label: 'Recife' },
      { value: 'porto-alegre', label: 'Porto Alegre' },
      { value: 'goiania', label: 'Goiânia' },
      { value: 'belem', label: 'Belém' },
      { value: 'guarulhos', label: 'Guarulhos' },
      { value: 'campinas', label: 'Campinas' },
      { value: 'sao-luis', label: 'São Luís' },
      { value: 'sao-goncalo', label: 'São Gonçalo' },
      { value: 'maceio', label: 'Maceió' },
      { value: 'duque-de-caxias', label: 'Duque de Caxias' },
      { value: 'natal', label: 'Natal' },
      { value: 'teresina', label: 'Teresina' },
      { value: 'sao-bernardo-do-campo', label: 'São Bernardo do Campo' },
      { value: 'nova-iguacu', label: 'Nova Iguaçu' },
      { value: 'joao-pessoa', label: 'João Pessoa' },
      { value: 'santo-andre', label: 'Santo André' },
      { value: 'osasco', label: 'Osasco' },
      { value: 'jaboatao-dos-guararapes', label: 'Jaboatão dos Guararapes' },
      { value: 'sao-jose-dos-campos', label: 'São José dos Campos' },
      { value: 'ribeirao-preto', label: 'Ribeirão Preto' },
      { value: 'uberlandia', label: 'Uberlândia' },
      { value: 'sorocaba', label: 'Sorocaba' },
      { value: 'contagem', label: 'Contagem' },
      { value: 'aracaju', label: 'Aracaju' },
      { value: 'feira-de-santana', label: 'Feira de Santana' },
      { value: 'cuiaba', label: 'Cuiabá' },
      { value: 'joinville', label: 'Joinville' },
      { value: 'apucarana', label: 'Apucarana' },
    ],
  },
  { value: 'bn', label: 'Brunei', code: 'BN', cities: [] },
  { value: 'bg', label: 'Bulgaria', code: 'BG', cities: [] },
  { value: 'bf', label: 'Burkina Faso', code: 'BF', cities: [] },
  { value: 'bi', label: 'Burundi', code: 'BI', cities: [] },
  
  // C
  { value: 'kh', label: 'Cambodia', code: 'KH', cities: [] },
  { value: 'cm', label: 'Cameroon', code: 'CM', cities: [] },
  {
    value: 'ca',
    label: 'Canada',
    code: 'CA',
    cities: [
      { value: 'toronto', label: 'Toronto' },
      { value: 'montreal', label: 'Montreal' },
      { value: 'vancouver', label: 'Vancouver' },
      { value: 'calgary', label: 'Calgary' },
      { value: 'edmonton', label: 'Edmonton' },
      { value: 'ottawa', label: 'Ottawa' },
      { value: 'winnipeg', label: 'Winnipeg' },
      { value: 'quebec-city', label: 'Quebec City' },
      { value: 'hamilton', label: 'Hamilton' },
      { value: 'kitchener', label: 'Kitchener' },
      { value: 'london', label: 'London' },
      { value: 'halifax', label: 'Halifax' },
      { value: 'victoria', label: 'Victoria' },
      { value: 'windsor', label: 'Windsor' },
      { value: 'oshawa', label: 'Oshawa' },
      { value: 'saskatoon', label: 'Saskatoon' },
      { value: 'regina', label: 'Regina' },
      { value: 'sherbrooke', label: 'Sherbrooke' },
      { value: 'kelowna', label: 'Kelowna' },
      { value: 'barrie', label: 'Barrie' },
      { value: 'abbotsford', label: 'Abbotsford' },
      { value: 'sudbury', label: 'Sudbury' },
      { value: 'kingston', label: 'Kingston' },
      { value: 'saguenay', label: 'Saguenay' },
      { value: 'trois-rivieres', label: 'Trois-Rivières' },
      { value: 'guelph', label: 'Guelph' },
      { value: 'cambridge', label: 'Cambridge' },
      { value: 'coquitlam', label: 'Coquitlam' },
      { value: 'richmond', label: 'Richmond' },
      { value: 'laval', label: 'Laval' },
      { value: 'surrey', label: 'Surrey' },
      { value: 'longueuil', label: 'Longueuil' },
      { value: 'burnaby', label: 'Burnaby' },
      { value: 'saint-catharines', label: 'Saint Catharines' },
      { value: 'thunder-bay', label: 'Thunder Bay' },
    ],
  },
  { value: 'cv', label: 'Cape Verde', code: 'CV', cities: [] },
  { value: 'cf', label: 'Central African Republic', code: 'CF', cities: [] },
  { value: 'td', label: 'Chad', code: 'TD', cities: [] },
  {
    value: 'cl',
    label: 'Chile',
    code: 'CL',
    cities: [
      { value: 'santiago', label: 'Santiago' },
      { value: 'valparaiso', label: 'Valparaíso' },
      { value: 'concepcion', label: 'Concepción' },
      { value: 'la-serena', label: 'La Serena' },
      { value: 'antofagasta', label: 'Antofagasta' },
      { value: 'temuco', label: 'Temuco' },
      { value: 'valdivia', label: 'Valdivia' },
      { value: 'arica', label: 'Arica' },
    ],
  },
  {
    value: 'cn',
    label: 'China',
    code: 'CN',
    cities: [
      { value: 'beijing', label: 'Beijing' },
      { value: 'shanghai', label: 'Shanghai' },
      { value: 'guangzhou', label: 'Guangzhou' },
      { value: 'shenzhen', label: 'Shenzhen' },
      { value: 'chengdu', label: 'Chengdu' },
      { value: 'hangzhou', label: 'Hangzhou' },
      { value: 'wuhan', label: 'Wuhan' },
      { value: 'xi-an', label: "Xi'an" },
      { value: 'nanjing', label: 'Nanjing' },
      { value: 'tianjin', label: 'Tianjin' },
      { value: 'chongqing', label: 'Chongqing' },
      { value: 'dongguan', label: 'Dongguan' },
      { value: 'shenyang', label: 'Shenyang' },
      { value: 'dalian', label: 'Dalian' },
      { value: 'qingdao', label: 'Qingdao' },
      { value: 'zhengzhou', label: 'Zhengzhou' },
      { value: 'jinan', label: 'Jinan' },
      { value: 'changsha', label: 'Changsha' },
      { value: 'kunming', label: 'Kunming' },
      { value: 'foshan', label: 'Foshan' },
      { value: 'suzhou', label: 'Suzhou' },
      { value: 'hefei', label: 'Hefei' },
      { value: 'xiamen', label: 'Xiamen' },
      { value: 'nanchang', label: 'Nanchang' },
      { value: 'shijiazhuang', label: 'Shijiazhuang' },
      { value: 'fuzhou', label: 'Fuzhou' },
      { value: 'wenzhou', label: 'Wenzhou' },
      { value: 'changchun', label: 'Changchun' },
      { value: 'tangshan', label: 'Tangshan' },
      { value: 'zibo', label: 'Zibo' },
      { value: 'taiyuan', label: 'Taiyuan' },
      { value: 'guiyang', label: 'Guiyang' },
      { value: 'wuxi', label: 'Wuxi' },
      { value: 'urumqi', label: 'Ürümqi' },
      { value: 'shantou', label: 'Shantou' },
      { value: 'haerbin', label: 'Harbin' },
      { value: 'nanning', label: 'Nanning' },
      { value: 'lanzhou', label: 'Lanzhou' },
      { value: 'baotou', label: 'Baotou' },
      { value: 'xuzhou', label: 'Xuzhou' },
      { value: 'yinchuan', label: 'Yinchuan' },
      { value: 'lhasa', label: 'Lhasa' },
    ],
  },
  {
    value: 'co',
    label: 'Colombia',
    code: 'CO',
    cities: [
      { value: 'bogota', label: 'Bogotá' },
      { value: 'medellin', label: 'Medellín' },
      { value: 'cali', label: 'Cali' },
      { value: 'barranquilla', label: 'Barranquilla' },
      { value: 'cartagena', label: 'Cartagena' },
      { value: 'cucuta', label: 'Cúcuta' },
      { value: 'bucaramanga', label: 'Bucaramanga' },
      { value: 'pereira', label: 'Pereira' },
    ],
  },
  { value: 'km', label: 'Comoros', code: 'KM', cities: [] },
  { value: 'cg', label: 'Congo (Republic of the)', code: 'CG', cities: [] },
  { value: 'cr', label: 'Costa Rica', code: 'CR', cities: [] },
  { value: 'hr', label: 'Croatia', code: 'HR', cities: [] },
  { value: 'cu', label: 'Cuba', code: 'CU', cities: [] },
  { value: 'cy', label: 'Cyprus', code: 'CY', cities: [] },
  { value: 'cz', label: 'Czech Republic', code: 'CZ', cities: [] },
  
  // D
  { value: 'dk', label: 'Denmark', code: 'DK', cities: [] },
  { value: 'dj', label: 'Djibouti', code: 'DJ', cities: [] },
  { value: 'dm', label: 'Dominica', code: 'DM', cities: [] },
  { value: 'do', label: 'Dominican Republic', code: 'DO', cities: [] },
  
  // E
  { value: 'ec', label: 'Ecuador', code: 'EC', cities: [] },
  {
    value: 'eg',
    label: 'Egypt',
    code: 'EG',
    cities: [
      { value: 'cairo', label: 'Cairo' },
      { value: 'alexandria', label: 'Alexandria' },
      { value: 'giza', label: 'Giza' },
      { value: 'shubra-el-kheima', label: 'Shubra El Kheima' },
      { value: 'port-said', label: 'Port Said' },
      { value: 'suez', label: 'Suez' },
      { value: 'luxor', label: 'Luxor' },
      { value: 'aswan', label: 'Aswan' },
      { value: 'mansoura', label: 'Mansoura' },
      { value: 'tanta', label: 'Tanta' },
      { value: 'ismailia', label: 'Ismailia' },
      { value: 'assiut', label: 'Assiut' },
      { value: 'zagazig', label: 'Zagazig' },
      { value: 'suez', label: 'Suez' },
      { value: 'damietta', label: 'Damietta' },
      { value: 'minya', label: 'Minya' },
      { value: 'sohag', label: 'Sohag' },
      { value: 'beni-suef', label: 'Beni Suef' },
      { value: 'qena', label: 'Qena' },
      { value: 'hurghada', label: 'Hurghada' },
      { value: 'sharm-el-sheikh', label: 'Sharm El Sheikh' },
      { value: 'marsa-matruh', label: 'Marsa Matruh' },
      { value: 'damanhur', label: 'Damanhur' },
      { value: 'kafr-el-sheikh', label: 'Kafr El Sheikh' },
      { value: 'banha', label: 'Banha' },
      { value: 'arish', label: 'Arish' },
      { value: 'mallawi', label: 'Mallawi' },
      { value: 'idku', label: 'Idku' },
      { value: 'mit-ghamr', label: 'Mit Ghamr' },
      { value: 'al-hamul', label: 'Al Hamul' },
      { value: 'desouk', label: 'Desouk' },
      { value: 'qalyub', label: 'Qalyub' },
      { value: 'abu-kabir', label: 'Abu Kabir' },
      { value: 'kafr-el-dawwar', label: 'Kafr El Dawwar' },
      { value: 'girga', label: 'Girga' },
      { value: 'akhmim', label: 'Akhmim' },
      { value: 'matareya', label: 'Matareya' },
    ],
  },
  { value: 'sv', label: 'El Salvador', code: 'SV', cities: [] },
  { value: 'gq', label: 'Equatorial Guinea', code: 'GQ', cities: [] },
  { value: 'er', label: 'Eritrea', code: 'ER', cities: [] },
  { value: 'ee', label: 'Estonia', code: 'EE', cities: [] },
  { value: 'sz', label: 'Eswatini', code: 'SZ', cities: [] },
  { value: 'et', label: 'Ethiopia', code: 'ET', cities: [] },
  
  // F
  { value: 'fj', label: 'Fiji', code: 'FJ', cities: [] },
  { value: 'fi', label: 'Finland', code: 'FI', cities: [] },
  {
    value: 'fr',
    label: 'France',
    code: 'FR',
    cities: [
      { value: 'paris', label: 'Paris' },
      { value: 'lyon', label: 'Lyon' },
      { value: 'marseille', label: 'Marseille' },
      { value: 'toulouse', label: 'Toulouse' },
      { value: 'nice', label: 'Nice' },
      { value: 'nantes', label: 'Nantes' },
      { value: 'strasbourg', label: 'Strasbourg' },
      { value: 'montpellier', label: 'Montpellier' },
      { value: 'bordeaux', label: 'Bordeaux' },
      { value: 'lille', label: 'Lille' },
      { value: 'rennes', label: 'Rennes' },
      { value: 'reims', label: 'Reims' },
      { value: 'saint-etienne', label: 'Saint-Étienne' },
      { value: 'toulon', label: 'Toulon' },
      { value: 'le-havre', label: 'Le Havre' },
      { value: 'grenoble', label: 'Grenoble' },
      { value: 'dijon', label: 'Dijon' },
      { value: 'angers', label: 'Angers' },
      { value: 'nimes', label: 'Nîmes' },
      { value: 'villeurbanne', label: 'Villeurbanne' },
      { value: 'saint-denis', label: 'Saint-Denis' },
      { value: 'le-mans', label: 'Le Mans' },
      { value: 'aix-en-provence', label: 'Aix-en-Provence' },
      { value: 'clermont-ferrand', label: 'Clermont-Ferrand' },
      { value: 'brest', label: 'Brest' },
      { value: 'limoges', label: 'Limoges' },
      { value: 'tours', label: 'Tours' },
      { value: 'amiens', label: 'Amiens' },
      { value: 'perpignan', label: 'Perpignan' },
      { value: 'metz', label: 'Metz' },
      { value: 'besancon', label: 'Besançon' },
      { value: 'boulogne-billancourt', label: 'Boulogne-Billancourt' },
      { value: 'orleans', label: 'Orléans' },
      { value: 'mulhouse', label: 'Mulhouse' },
      { value: 'rouen', label: 'Rouen' },
      { value: 'caen', label: 'Caen' },
      { value: 'nancy', label: 'Nancy' },
    ],
  },
  
  // G
  { value: 'ga', label: 'Gabon', code: 'GA', cities: [] },
  { value: 'gm', label: 'Gambia', code: 'GM', cities: [] },
  { value: 'ge', label: 'Georgia', code: 'GE', cities: [] },
  {
    value: 'de',
    label: 'Germany',
    code: 'DE',
    cities: [
      { value: 'berlin', label: 'Berlin' },
      { value: 'munich', label: 'Munich' },
      { value: 'hamburg', label: 'Hamburg' },
      { value: 'frankfurt', label: 'Frankfurt' },
      { value: 'cologne', label: 'Cologne' },
      { value: 'stuttgart', label: 'Stuttgart' },
      { value: 'dusseldorf', label: 'Düsseldorf' },
      { value: 'dortmund', label: 'Dortmund' },
      { value: 'essen', label: 'Essen' },
      { value: 'leipzig', label: 'Leipzig' },
      { value: 'bremen', label: 'Bremen' },
      { value: 'dresden', label: 'Dresden' },
      { value: 'hannover', label: 'Hannover' },
      { value: 'nuremberg', label: 'Nuremberg' },
      { value: 'duisburg', label: 'Duisburg' },
      { value: 'bochum', label: 'Bochum' },
      { value: 'wuppertal', label: 'Wuppertal' },
      { value: 'bielefeld', label: 'Bielefeld' },
      { value: 'bonn', label: 'Bonn' },
      { value: 'munster', label: 'Münster' },
      { value: 'karlsruhe', label: 'Karlsruhe' },
      { value: 'mannheim', label: 'Mannheim' },
      { value: 'augsburg', label: 'Augsburg' },
      { value: 'wiesbaden', label: 'Wiesbaden' },
      { value: 'gelsenkirchen', label: 'Gelsenkirchen' },
      { value: 'monchengladbach', label: 'Mönchengladbach' },
      { value: 'braunschweig', label: 'Braunschweig' },
      { value: 'chemnitz', label: 'Chemnitz' },
      { value: 'kiel', label: 'Kiel' },
      { value: 'aachen', label: 'Aachen' },
      { value: 'halle', label: 'Halle' },
      { value: 'magdeburg', label: 'Magdeburg' },
      { value: 'freiburg', label: 'Freiburg' },
      { value: 'krefeld', label: 'Krefeld' },
      { value: 'lubeck', label: 'Lübeck' },
      { value: 'oberhausen', label: 'Oberhausen' },
      { value: 'erfurt', label: 'Erfurt' },
      { value: 'mainz', label: 'Mainz' },
      { value: 'rostock', label: 'Rostock' },
      { value: 'kassel', label: 'Kassel' },
    ],
  },
  { value: 'gh', label: 'Ghana', code: 'GH', cities: [] },
  { value: 'gr', label: 'Greece', code: 'GR', cities: [] },
  { value: 'gd', label: 'Grenada', code: 'GD', cities: [] },
  { value: 'gt', label: 'Guatemala', code: 'GT', cities: [] },
  { value: 'gn', label: 'Guinea', code: 'GN', cities: [] },
  { value: 'gw', label: 'Guinea-Bissau', code: 'GW', cities: [] },
  { value: 'gy', label: 'Guyana', code: 'GY', cities: [] },
  
  // H
  { value: 'ht', label: 'Haiti', code: 'HT', cities: [] },
  { value: 'hn', label: 'Honduras', code: 'HN', cities: [] },
  { value: 'hu', label: 'Hungary', code: 'HU', cities: [] },
  
  // I
  { value: 'is', label: 'Iceland', code: 'IS', cities: [] },
  {
    value: 'in',
    label: 'India',
    code: 'IN',
    cities: [
      { value: 'mumbai', label: 'Mumbai' },
      { value: 'delhi', label: 'Delhi' },
      { value: 'bangalore', label: 'Bangalore' },
      { value: 'hyderabad', label: 'Hyderabad' },
      { value: 'chennai', label: 'Chennai' },
      { value: 'kolkata', label: 'Kolkata' },
      { value: 'pune', label: 'Pune' },
      { value: 'ahmedabad', label: 'Ahmedabad' },
      { value: 'jaipur', label: 'Jaipur' },
      { value: 'surat', label: 'Surat' },
      { value: 'lucknow', label: 'Lucknow' },
      { value: 'kanpur', label: 'Kanpur' },
      { value: 'nagpur', label: 'Nagpur' },
      { value: 'indore', label: 'Indore' },
      { value: 'thane', label: 'Thane' },
      { value: 'bhopal', label: 'Bhopal' },
      { value: 'visakhapatnam', label: 'Visakhapatnam' },
      { value: 'patna', label: 'Patna' },
      { value: 'vadodara', label: 'Vadodara' },
      { value: 'ghaziabad', label: 'Ghaziabad' },
      { value: 'ludhiana', label: 'Ludhiana' },
      { value: 'agra', label: 'Agra' },
      { value: 'nashik', label: 'Nashik' },
      { value: 'faridabad', label: 'Faridabad' },
      { value: 'meerut', label: 'Meerut' },
      { value: 'rajkot', label: 'Rajkot' },
      { value: 'varanasi', label: 'Varanasi' },
      { value: 'srinagar', label: 'Srinagar' },
      { value: 'amritsar', label: 'Amritsar' },
      { value: 'chandigarh', label: 'Chandigarh' },
      { value: 'jodhpur', label: 'Jodhpur' },
      { value: 'raipur', label: 'Raipur' },
      { value: 'kota', label: 'Kota' },
      { value: 'guwahati', label: 'Guwahati' },
      { value: 'bhubaneswar', label: 'Bhubaneswar' },
      { value: 'coimbatore', label: 'Coimbatore' },
      { value: 'vijayawada', label: 'Vijayawada' },
      { value: 'madurai', label: 'Madurai' },
      { value: 'jalandhar', label: 'Jalandhar' },
      { value: 'gwalior', label: 'Gwalior' },
      { value: 'jamshedpur', label: 'Jamshedpur' },
    ],
  },
  {
    value: 'id',
    label: 'Indonesia',
    code: 'ID',
    cities: [
      { value: 'jakarta', label: 'Jakarta' },
      { value: 'surabaya', label: 'Surabaya' },
      { value: 'bandung', label: 'Bandung' },
      { value: 'medan', label: 'Medan' },
      { value: 'semarang', label: 'Semarang' },
      { value: 'makassar', label: 'Makassar' },
      { value: 'palembang', label: 'Palembang' },
      { value: 'tangerang', label: 'Tangerang' },
    ],
  },
  {
    value: 'ir',
    label: 'Iran',
    code: 'IR',
    cities: [
      { value: 'tehran', label: 'Tehran' },
      { value: 'mashhad', label: 'Mashhad' },
      { value: 'isfahan', label: 'Isfahan' },
      { value: 'karaj', label: 'Karaj' },
      { value: 'shiraz', label: 'Shiraz' },
      { value: 'tabriz', label: 'Tabriz' },
      { value: 'qom', label: 'Qom' },
      { value: 'ahvaz', label: 'Ahvaz' },
    ],
  },
  {
    value: 'iq',
    label: 'Iraq',
    code: 'IQ',
    cities: [
      { value: 'baghdad', label: 'Baghdad' },
      { value: 'basra', label: 'Basra' },
      { value: 'mosul', label: 'Mosul' },
      { value: 'erbil', label: 'Erbil' },
      { value: 'kirkuk', label: 'Kirkuk' },
      { value: 'najaf', label: 'Najaf' },
      { value: 'karbala', label: 'Karbala' },
      { value: 'sulaymaniyah', label: 'Sulaymaniyah' },
    ],
  },
  { value: 'ie', label: 'Ireland', code: 'IE', cities: [] },
  { value: 'il', label: 'Israel', code: 'IL', cities: [] },
  {
    value: 'it',
    label: 'Italy',
    code: 'IT',
    cities: [
      { value: 'rome', label: 'Rome' },
      { value: 'milan', label: 'Milan' },
      { value: 'naples', label: 'Naples' },
      { value: 'turin', label: 'Turin' },
      { value: 'palermo', label: 'Palermo' },
      { value: 'genoa', label: 'Genoa' },
      { value: 'bologna', label: 'Bologna' },
      { value: 'florence', label: 'Florence' },
      { value: 'bari', label: 'Bari' },
      { value: 'catania', label: 'Catania' },
    ],
  },
  
  // J
  { value: 'jm', label: 'Jamaica', code: 'JM', cities: [] },
  {
    value: 'jp',
    label: 'Japan',
    code: 'JP',
    cities: [
      { value: 'tokyo', label: 'Tokyo' },
      { value: 'yokohama', label: 'Yokohama' },
      { value: 'osaka', label: 'Osaka' },
      { value: 'nagoya', label: 'Nagoya' },
      { value: 'sapporo', label: 'Sapporo' },
      { value: 'fukuoka', label: 'Fukuoka' },
      { value: 'kobe', label: 'Kobe' },
      { value: 'kyoto', label: 'Kyoto' },
      { value: 'kawasaki', label: 'Kawasaki' },
      { value: 'saitama', label: 'Saitama' },
      { value: 'hiroshima', label: 'Hiroshima' },
      { value: 'sendai', label: 'Sendai' },
      { value: 'chiba', label: 'Chiba' },
      { value: 'kitakyushu', label: 'Kitakyushu' },
      { value: 'sakai', label: 'Sakai' },
      { value: 'niigata', label: 'Niigata' },
      { value: 'hamamatsu', label: 'Hamamatsu' },
      { value: 'kumamoto', label: 'Kumamoto' },
      { value: 'sagamihara', label: 'Sagamihara' },
      { value: 'shizuoka', label: 'Shizuoka' },
      { value: 'okayama', label: 'Okayama' },
      { value: 'hachioji', label: 'Hachioji' },
      { value: 'kagoshima', label: 'Kagoshima' },
      { value: 'funabashi', label: 'Funabashi' },
      { value: 'matsuyama', label: 'Matsuyama' },
      { value: 'higashiosaka', label: 'Higashiosaka' },
      { value: 'kawaguchi', label: 'Kawaguchi' },
      { value: 'kanazawa', label: 'Kanazawa' },
      { value: 'gifu', label: 'Gifu' },
      { value: 'nagano', label: 'Nagano' },
      { value: 'toyonaka', label: 'Toyonaka' },
      { value: 'nara', label: 'Nara' },
      { value: 'toyohashi', label: 'Toyohashi' },
      { value: 'toyama', label: 'Toyama' },
      { value: 'akita', label: 'Akita' },
      { value: 'matsudo', label: 'Matsudo' },
      { value: 'utsunomiya', label: 'Utsunomiya' },
      { value: 'otsu', label: 'Otsu' },
      { value: 'yamagata', label: 'Yamagata' },
      { value: 'fukushima', label: 'Fukushima' },
      { value: 'maebashi', label: 'Maebashi' },
      { value: 'morioka', label: 'Morioka' },
      { value: 'aomori', label: 'Aomori' },
      { value: 'takamatsu', label: 'Takamatsu' },
      { value: 'kochi', label: 'Kochi' },
      { value: 'tokushima', label: 'Tokushima' },
      { value: 'tottori', label: 'Tottori' },
      { value: 'matsue', label: 'Matsue' },
      { value: 'yamaguchi', label: 'Yamaguchi' },
      { value: 'saga', label: 'Saga' },
      { value: 'miyazaki', label: 'Miyazaki' },
      { value: 'naha', label: 'Naha' },
    ],
  },
  { value: 'jo', label: 'Jordan', code: 'JO', cities: [] },
  
  // K
  { value: 'kz', label: 'Kazakhstan', code: 'KZ', cities: [] },
  {
    value: 'ke',
    label: 'Kenya',
    code: 'KE',
    cities: [
      { value: 'nairobi', label: 'Nairobi' },
      { value: 'mombasa', label: 'Mombasa' },
      { value: 'kisumu', label: 'Kisumu' },
      { value: 'nakuru', label: 'Nakuru' },
      { value: 'eldoret', label: 'Eldoret' },
      { value: 'thika', label: 'Thika' },
      { value: 'malindi', label: 'Malindi' },
      { value: 'kitale', label: 'Kitale' },
    ],
  },
  { value: 'ki', label: 'Kiribati', code: 'KI', cities: [] },
  { value: 'kp', label: 'North Korea', code: 'KP', cities: [] },
  { value: 'kr', label: 'South Korea', code: 'KR', cities: [
      { value: 'seoul', label: 'Seoul' },
      { value: 'busan', label: 'Busan' },
      { value: 'incheon', label: 'Incheon' },
      { value: 'daegu', label: 'Daegu' },
      { value: 'daejeon', label: 'Daejeon' },
      { value: 'gwangju', label: 'Gwangju' },
      { value: 'suwon', label: 'Suwon' },
      { value: 'ulsan', label: 'Ulsan' },
    { value: 'goyang', label: 'Goyang' },
    { value: 'yongin', label: 'Yongin' },
    { value: 'changwon', label: 'Changwon' },
    { value: 'seongnam', label: 'Seongnam' },
    { value: 'bucheon', label: 'Bucheon' },
    { value: 'ansan', label: 'Ansan' },
    { value: 'anyang', label: 'Anyang' },
    { value: 'jeonju', label: 'Jeonju' },
    { value: 'cheonan', label: 'Cheonan' },
    { value: 'namyangju', label: 'Namyangju' },
    { value: 'hwaseong', label: 'Hwaseong' },
    { value: 'gimhae', label: 'Gimhae' },
    { value: 'pyeongtaek', label: 'Pyeongtaek' },
    { value: 'gumi', label: 'Gumi' },
    { value: 'jinju', label: 'Jinju' },
    { value: 'iksan', label: 'Iksan' },
    { value: 'mokpo', label: 'Mokpo' },
    { value: 'gunsan', label: 'Gunsan' },
    { value: 'yeosu', label: 'Yeosu' },
    { value: 'suncheon', label: 'Suncheon' },
    { value: 'jeju', label: 'Jeju' },
    { value: 'gangneung', label: 'Gangneung' },
    { value: 'chuncheon', label: 'Chuncheon' },
    { value: 'wonju', label: 'Wonju' },
    { value: 'cheongju', label: 'Cheongju' },
    { value: 'asan', label: 'Asan' },
    { value: 'pohang', label: 'Pohang' },
    { value: 'gyeongju', label: 'Gyeongju' },
    { value: 'masan', label: 'Masan' },
    { value: 'tongyeong', label: 'Tongyeong' },
    { value: 'geoje', label: 'Geoje' },
    { value: 'yangsan', label: 'Yangsan' },
    { value: 'gimcheon', label: 'Gimcheon' },
    { value: 'andong', label: 'Andong' },
    { value: 'sangju', label: 'Sangju' },
    { value: 'yeongju', label: 'Yeongju' },
    { value: 'jecheon', label: 'Jecheon' },
    { value: 'chungju', label: 'Chungju' },
    { value: 'sejong', label: 'Sejong' },
  ] },
  { value: 'kw', label: 'Kuwait', code: 'KW', cities: [] },
  { value: 'kg', label: 'Kyrgyzstan', code: 'KG', cities: [] },
  
  // L
  { value: 'la', label: 'Laos', code: 'LA', cities: [] },
  { value: 'lv', label: 'Latvia', code: 'LV', cities: [] },
  { value: 'lb', label: 'Lebanon', code: 'LB', cities: [] },
  { value: 'ls', label: 'Lesotho', code: 'LS', cities: [] },
  { value: 'lr', label: 'Liberia', code: 'LR', cities: [] },
  { value: 'ly', label: 'Libya', code: 'LY', cities: [] },
  { value: 'li', label: 'Liechtenstein', code: 'LI', cities: [] },
  { value: 'lt', label: 'Lithuania', code: 'LT', cities: [] },
  { value: 'lu', label: 'Luxembourg', code: 'LU', cities: [] },
  
  // M
  { value: 'mg', label: 'Madagascar', code: 'MG', cities: [] },
  { value: 'mw', label: 'Malawi', code: 'MW', cities: [] },
  {
    value: 'my',
    label: 'Malaysia',
    code: 'MY',
    cities: [
      { value: 'kuala-lumpur', label: 'Kuala Lumpur' },
      { value: 'george-town', label: 'George Town' },
      { value: 'ipoh', label: 'Ipoh' },
      { value: 'shah-alam', label: 'Shah Alam' },
      { value: 'petaling-jaya', label: 'Petaling Jaya' },
      { value: 'johor-bahru', label: 'Johor Bahru' },
      { value: 'melaka', label: 'Melaka' },
      { value: 'kuching', label: 'Kuching' },
      { value: 'kota-kinabalu', label: 'Kota Kinabalu' },
      { value: 'kuala-terengganu', label: 'Kuala Terengganu' },
      { value: 'alor-setar', label: 'Alor Setar' },
      { value: 'seremban', label: 'Seremban' },
      { value: 'subang-jaya', label: 'Subang Jaya' },
      { value: 'klang', label: 'Klang' },
      { value: 'kajang', label: 'Kajang' },
      { value: 'selayang', label: 'Selayang' },
      { value: 'ampang', label: 'Ampang' },
      { value: 'kota-bharu', label: 'Kota Bharu' },
      { value: 'miri', label: 'Miri' },
      { value: 'taiping', label: 'Taiping' },
      { value: 'sibu', label: 'Sibu' },
      { value: 'sandakan', label: 'Sandakan' },
      { value: 'tawau', label: 'Tawau' },
      { value: 'labuan', label: 'Labuan' },
      { value: 'putrajaya', label: 'Putrajaya' },
      { value: 'cyberjaya', label: 'Cyberjaya' },
      { value: 'nilai', label: 'Nilai' },
      { value: 'senai', label: 'Senai' },
      { value: 'kulim', label: 'Kulim' },
      { value: 'batu-pahat', label: 'Batu Pahat' },
      { value: 'muar', label: 'Muar' },
      { value: 'rawang', label: 'Rawang' },
      { value: 'butterworth', label: 'Butterworth' },
      { value: 'kangar', label: 'Kangar' },
      { value: 'jitra', label: 'Jitra' },
      { value: 'sungai-petani', label: 'Sungai Petani' },
      { value: 'kuantan', label: 'Kuantan' },
      { value: 'temerloh', label: 'Temerloh' },
      { value: 'bentong', label: 'Bentong' },
      { value: 'raub', label: 'Raub' },
      { value: 'jerantut', label: 'Jerantut' },
      { value: 'kemaman', label: 'Kemaman' },
      { value: 'dungun', label: 'Dungun' },
      { value: 'marang', label: 'Marang' },
      { value: 'besut', label: 'Besut' },
      { value: 'setiu', label: 'Setiu' },
      { value: 'hulu-terengganu', label: 'Hulu Terengganu' },
    ],
  },
  { value: 'mv', label: 'Maldives', code: 'MV', cities: [] },
  { value: 'ml', label: 'Mali', code: 'ML', cities: [] },
  { value: 'mt', label: 'Malta', code: 'MT', cities: [] },
  { value: 'mh', label: 'Marshall Islands', code: 'MH', cities: [] },
  { value: 'mr', label: 'Mauritania', code: 'MR', cities: [] },
  { value: 'mu', label: 'Mauritius', code: 'MU', cities: [] },
  {
    value: 'mx',
    label: 'Mexico',
    code: 'MX',
    cities: [
      { value: 'mexico-city', label: 'Mexico City' },
      { value: 'guadalajara', label: 'Guadalajara' },
      { value: 'monterrey', label: 'Monterrey' },
      { value: 'puebla', label: 'Puebla' },
      { value: 'tijuana', label: 'Tijuana' },
      { value: 'leon', label: 'León' },
      { value: 'juarez', label: 'Juárez' },
      { value: 'torreon', label: 'Torreón' },
      { value: 'queretaro', label: 'Querétaro' },
      { value: 'san-luis-potosi', label: 'San Luis Potosí' },
      { value: 'merida', label: 'Mérida' },
      { value: 'mexicali', label: 'Mexicali' },
      { value: 'toluca', label: 'Toluca' },
      { value: 'cancun', label: 'Cancún' },
      { value: 'chihuahua', label: 'Chihuahua' },
      { value: 'saltillo', label: 'Saltillo' },
      { value: 'aguascalientes', label: 'Aguascalientes' },
      { value: 'cuernavaca', label: 'Cuernavaca' },
      { value: 'acapulco', label: 'Acapulco' },
      { value: 'tampico', label: 'Tampico' },
      { value: 'veracruz', label: 'Veracruz' },
      { value: 'morelia', label: 'Morelia' },
      { value: 'hermosillo', label: 'Hermosillo' },
      { value: 'culiacan', label: 'Culiacán' },
      { value: 'xalapa', label: 'Xalapa' },
      { value: 'mazatlan', label: 'Mazatlán' },
      { value: 'durango', label: 'Durango' },
      { value: 'tuxtla-gutierrez', label: 'Tuxtla Gutiérrez' },
      { value: 'ciudad-victoria', label: 'Ciudad Victoria' },
      { value: 'tlaxcala', label: 'Tlaxcala' },
      { value: 'campeche', label: 'Campeche' },
      { value: 'oaxaca', label: 'Oaxaca' },
      { value: 'colima', label: 'Colima' },
      { value: 'villahermosa', label: 'Villahermosa' },
      { value: 'chetumal', label: 'Chetumal' },
      { value: 'chilpancingo', label: 'Chilpancingo' },
      { value: 'pachuca', label: 'Pachuca' },
      { value: 'zacatecas', label: 'Zacatecas' },
      { value: 'san-cristobal-de-las-casas', label: 'San Cristóbal de las Casas' },
      { value: 'puerto-vallarta', label: 'Puerto Vallarta' },
      { value: 'playa-del-carmen', label: 'Playa del Carmen' },
      { value: 'tulum', label: 'Tulum' },
      { value: 'cozumel', label: 'Cozumel' },
      { value: 'ensenada', label: 'Ensenada' },
      { value: 'rosarito', label: 'Rosarito' },
      { value: 'la-paz', label: 'La Paz' },
      { value: 'los-cabos', label: 'Los Cabos' },
      { value: 'ciudad-del-carmen', label: 'Ciudad del Carmen' },
      { value: 'progreso', label: 'Progreso' },
      { value: 'valladolid', label: 'Valladolid' },
      { value: 'izamal', label: 'Izamal' },
      { value: 'san-miguel-de-allende', label: 'San Miguel de Allende' },
      { value: 'guanajuato', label: 'Guanajuato' },
      { value: 'san-cristobal', label: 'San Cristóbal' },
      { value: 'taxco', label: 'Taxco' },
      { value: 'tequila', label: 'Tequila' },
      { value: 'teotihuacan', label: 'Teotihuacán' },
      { value: 'chichen-itza', label: 'Chichén Itzá' },
      { value: 'palenque', label: 'Palenque' },
      { value: 'uxmal', label: 'Uxmal' },
    ],
  },
  { value: 'fm', label: 'Micronesia', code: 'FM', cities: [] },
  { value: 'md', label: 'Moldova', code: 'MD', cities: [] },
  { value: 'mc', label: 'Monaco', code: 'MC', cities: [] },
  { value: 'mn', label: 'Mongolia', code: 'MN', cities: [] },
  { value: 'me', label: 'Montenegro', code: 'ME', cities: [] },
  { value: 'ma', label: 'Morocco', code: 'MA', cities: [] },
  { value: 'mz', label: 'Mozambique', code: 'MZ', cities: [] },
  { value: 'mm', label: 'Myanmar', code: 'MM', cities: [] },
  
  // N
  { value: 'na', label: 'Namibia', code: 'NA', cities: [] },
  { value: 'nr', label: 'Nauru', code: 'NR', cities: [] },
  { value: 'np', label: 'Nepal', code: 'NP', cities: [] },
  {
    value: 'nl',
    label: 'Netherlands',
    code: 'NL',
    cities: [
      { value: 'amsterdam', label: 'Amsterdam' },
      { value: 'rotterdam', label: 'Rotterdam' },
      { value: 'the-hague', label: 'The Hague' },
      { value: 'utrecht', label: 'Utrecht' },
      { value: 'eindhoven', label: 'Eindhoven' },
      { value: 'groningen', label: 'Groningen' },
      { value: 'tilburg', label: 'Tilburg' },
      { value: 'almere', label: 'Almere' },
    ],
  },
  {
    value: 'nz',
    label: 'New Zealand',
    code: 'NZ',
    cities: [
      { value: 'auckland', label: 'Auckland' },
      { value: 'wellington', label: 'Wellington' },
      { value: 'christchurch', label: 'Christchurch' },
      { value: 'hamilton', label: 'Hamilton' },
      { value: 'napier', label: 'Napier' },
      { value: 'dunedin', label: 'Dunedin' },
      { value: 'tauranga', label: 'Tauranga' },
      { value: 'lower-hutt', label: 'Lower Hutt' },
    ],
  },
  { value: 'ni', label: 'Nicaragua', code: 'NI', cities: [] },
  { value: 'ne', label: 'Niger', code: 'NE', cities: [] },
  {
    value: 'ng',
    label: 'Nigeria',
    code: 'NG',
    cities: [
      { value: 'lagos', label: 'Lagos' },
      { value: 'kano', label: 'Kano' },
      { value: 'ibadan', label: 'Ibadan' },
      { value: 'abuja', label: 'Abuja' },
      { value: 'port-harcourt', label: 'Port Harcourt' },
      { value: 'benin-city', label: 'Benin City' },
      { value: 'kaduna', label: 'Kaduna' },
    ],
  },
  { value: 'mk', label: 'North Macedonia', code: 'MK', cities: [] },
  { value: 'no', label: 'Norway', code: 'NO', cities: [] },
  
  // O
  { value: 'om', label: 'Oman', code: 'OM', cities: [] },
  
  // P
  {
    value: 'pk',
    label: 'Pakistan',
    code: 'PK',
    cities: [
      { value: 'karachi', label: 'Karachi' },
      { value: 'lahore', label: 'Lahore' },
      { value: 'islamabad', label: 'Islamabad' },
      { value: 'rawalpindi', label: 'Rawalpindi' },
      { value: 'faisalabad', label: 'Faisalabad' },
      { value: 'multan', label: 'Multan' },
      { value: 'peshawar', label: 'Peshawar' },
      { value: 'quetta', label: 'Quetta' },
      { value: 'sialkot', label: 'Sialkot' },
      { value: 'gujranwala', label: 'Gujranwala' },
      { value: 'hyderabad', label: 'Hyderabad' },
      { value: 'peshawar', label: 'Peshawar' },
      { value: 'abbottabad', label: 'Abbottabad' },
      { value: 'sargodha', label: 'Sargodha' },
      { value: 'bahawalpur', label: 'Bahawalpur' },
      { value: 'sukkur', label: 'Sukkur' },
      { value: 'jhang', label: 'Jhang' },
      { value: 'sheikhupura', label: 'Sheikhupura' },
      { value: 'mardan', label: 'Mardan' },
      { value: 'gujrat', label: 'Gujrat' },
      { value: 'kasur', label: 'Kasur' },
      { value: 'dera-ghazi-khan', label: 'Dera Ghazi Khan' },
      { value: 'sahiwal', label: 'Sahiwal' },
      { value: 'nawabshah', label: 'Nawabshah' },
      { value: 'chiniot', label: 'Chiniot' },
      { value: 'kotri', label: 'Kotri' },
      { value: 'khanpur', label: 'Khanpur' },
      { value: 'hafizabad', label: 'Hafizabad' },
      { value: 'kohat', label: 'Kohat' },
      { value: 'jacobabad', label: 'Jacobabad' },
      { value: 'shikarpur', label: 'Shikarpur' },
      { value: 'muzaffargarh', label: 'Muzaffargarh' },
      { value: 'khanewal', label: 'Khanewal' },
      { value: 'gojra', label: 'Gojra' },
      { value: 'bahawalnagar', label: 'Bahawalnagar' },
      { value: 'muridke', label: 'Muridke' },
      { value: 'pakpattan', label: 'Pakpattan' },
      { value: 'abad', label: 'Abad' },
      { value: 'chishtian', label: 'Chishtian' },
    ],
  },
  { value: 'ps', label: 'Palestine', code: 'PS', cities: [] },
  { value: 'pw', label: 'Palau', code: 'PW', cities: [] },
  { value: 'pa', label: 'Panama', code: 'PA', cities: [] },
  { value: 'pg', label: 'Papua New Guinea', code: 'PG', cities: [] },
  { value: 'py', label: 'Paraguay', code: 'PY', cities: [] },
  { value: 'pe', label: 'Peru', code: 'PE', cities: [] },
  {
    value: 'ph',
    label: 'Philippines',
    code: 'PH',
    cities: [
      { value: 'manila', label: 'Manila' },
      { value: 'quezon-city', label: 'Quezon City' },
      { value: 'cebu', label: 'Cebu' },
      { value: 'davao', label: 'Davao' },
      { value: 'caloocan', label: 'Caloocan' },
      { value: 'zamboanga', label: 'Zamboanga' },
      { value: 'antipolo', label: 'Antipolo' },
      { value: 'pasig', label: 'Pasig' },
    ],
  },
  {
    value: 'pl',
    label: 'Poland',
    code: 'PL',
    cities: [
      { value: 'warsaw', label: 'Warsaw' },
      { value: 'krakow', label: 'Kraków' },
      { value: 'lodz', label: 'Łódź' },
      { value: 'wroclaw', label: 'Wrocław' },
      { value: 'poznan', label: 'Poznań' },
      { value: 'gdansk', label: 'Gdańsk' },
      { value: 'szczecin', label: 'Szczecin' },
      { value: 'bydgoszcz', label: 'Bydgoszcz' },
    ],
  },
  { value: 'pt', label: 'Portugal', code: 'PT', cities: [] },
  
  // Q
  { value: 'qa', label: 'Qatar', code: 'QA', cities: [] },
  
  // R
  { value: 'ro', label: 'Romania', code: 'RO', cities: [] },
  {
    value: 'ru',
    label: 'Russia',
    code: 'RU',
    cities: [
      { value: 'moscow', label: 'Moscow' },
      { value: 'saint-petersburg', label: 'Saint Petersburg' },
      { value: 'novosibirsk', label: 'Novosibirsk' },
      { value: 'yekaterinburg', label: 'Yekaterinburg' },
      { value: 'kazan', label: 'Kazan' },
      { value: 'nizhny-novgorod', label: 'Nizhny Novgorod' },
      { value: 'chelyabinsk', label: 'Chelyabinsk' },
      { value: 'samara', label: 'Samara' },
      { value: 'omsk', label: 'Omsk' },
      { value: 'rostov-on-don', label: 'Rostov-on-Don' },
      { value: 'ufa', label: 'Ufa' },
      { value: 'krasnoyarsk', label: 'Krasnoyarsk' },
      { value: 'voronezh', label: 'Voronezh' },
      { value: 'perm', label: 'Perm' },
      { value: 'volgograd', label: 'Volgograd' },
      { value: 'krasnodar', label: 'Krasnodar' },
      { value: 'saratov', label: 'Saratov' },
      { value: 'tyumen', label: 'Tyumen' },
      { value: 'tolyatti', label: 'Tolyatti' },
      { value: 'izhevsk', label: 'Izhevsk' },
      { value: 'barnaul', label: 'Barnaul' },
      { value: 'ulyanovsk', label: 'Ulyanovsk' },
      { value: 'irkutsk', label: 'Irkutsk' },
      { value: 'khabarovsk', label: 'Khabarovsk' },
      { value: 'yaroslavl', label: 'Yaroslavl' },
      { value: 'vladivostok', label: 'Vladivostok' },
      { value: 'makhachkala', label: 'Makhachkala' },
      { value: 'tomsk', label: 'Tomsk' },
      { value: 'orenburg', label: 'Orenburg' },
      { value: 'kemerovo', label: 'Kemerovo' },
      { value: 'novokuznetsk', label: 'Novokuznetsk' },
      { value: 'ryazan', label: 'Ryazan' },
      { value: 'naberezhnye-chelny', label: 'Naberezhnye Chelny' },
      { value: 'astrakhan', label: 'Astrakhan' },
      { value: 'penza', label: 'Penza' },
      { value: 'lipetsk', label: 'Lipetsk' },
      { value: 'kirov', label: 'Kirov' },
      { value: 'cheboksary', label: 'Cheboksary' },
      { value: 'kaliningrad', label: 'Kaliningrad' },
      { value: 'tula', label: 'Tula' },
      { value: 'kursk', label: 'Kursk' },
      { value: 'stavropol', label: 'Stavropol' },
      { value: 'sochi', label: 'Sochi' },
      { value: 'tver', label: 'Tver' },
      { value: 'magnitogorsk', label: 'Magnitogorsk' },
      { value: 'ivanovo', label: 'Ivanovo' },
      { value: 'bryansk', label: 'Bryansk' },
      { value: 'surgut', label: 'Surgut' },
      { value: 'vladimir', label: 'Vladimir' },
      { value: 'nizhny-tagil', label: 'Nizhny Tagil' },
      { value: 'arhangelsk', label: 'Arkhangelsk' },
      { value: 'chita', label: 'Chita' },
      { value: 'smolensk', label: 'Smolensk' },
      { value: 'kaluga', label: 'Kaluga' },
      { value: 'belgorod', label: 'Belgorod' },
      { value: 'vologda', label: 'Vologda' },
      { value: 'kurgan', label: 'Kurgan' },
      { value: 'yakutsk', label: 'Yakutsk' },
      { value: 'petrozavodsk', label: 'Petrozavodsk' },
      { value: 'syktyvkar', label: 'Syktyvkar' },
      { value: 'murmansk', label: 'Murmansk' },
      { value: 'novgorod', label: 'Novgorod' },
      { value: 'pskov', label: 'Pskov' },
      { value: 'veliky-novgorod', label: 'Veliky Novgorod' },
      { value: 'kostroma', label: 'Kostroma' },
      { value: 'tambov', label: 'Tambov' },
      { value: 'sterlitamak', label: 'Sterlitamak' },
      { value: 'petropavlovsk-kamchatsky', label: 'Petropavlovsk-Kamchatsky' },
      { value: 'magadan', label: 'Magadan' },
      { value: 'anadyr', label: 'Anadyr' },
      { value: 'norilsk', label: 'Norilsk' },
      { value: 'dudinka', label: 'Dudinka' },
      { value: 'salekhard', label: 'Salekhard' },
      { value: 'naryan-mar', label: 'Naryan-Mar' },
      { value: 'syktyvkar', label: 'Syktyvkar' },
      { value: 'elista', label: 'Elista' },
      { value: 'grozny', label: 'Grozny' },
      { value: 'nalchik', label: 'Nalchik' },
      { value: 'vladikavkaz', label: 'Vladikavkaz' },
      { value: 'maykop', label: 'Maykop' },
      { value: 'cherkessk', label: 'Cherkessk' },
      { value: 'nizhny-novgorod', label: 'Nizhny Novgorod' },
      { value: 'chelyabinsk', label: 'Chelyabinsk' },
      { value: 'samara', label: 'Samara' },
    ],
  },
  { value: 'rw', label: 'Rwanda', code: 'RW', cities: [] },
  
  // S
  { value: 'kn', label: 'Saint Kitts and Nevis', code: 'KN', cities: [] },
  { value: 'lc', label: 'Saint Lucia', code: 'LC', cities: [] },
  { value: 'vc', label: 'Saint Vincent and the Grenadines', code: 'VC', cities: [] },
  { value: 'ws', label: 'Samoa', code: 'WS', cities: [] },
  { value: 'sm', label: 'San Marino', code: 'SM', cities: [] },
  { value: 'st', label: 'Sao Tome and Principe', code: 'ST', cities: [] },
  {
    value: 'sa',
    label: 'Saudi Arabia',
    code: 'SA',
    cities: [
      { value: 'riyadh', label: 'Riyadh' },
      { value: 'jeddah', label: 'Jeddah' },
      { value: 'mecca', label: 'Mecca' },
      { value: 'medina', label: 'Medina' },
      { value: 'dammam', label: 'Dammam' },
      { value: 'khobar', label: 'Khobar' },
      { value: 'taif', label: 'Taif' },
      { value: 'abha', label: 'Abha' },
      { value: 'buraydah', label: 'Buraydah' },
      { value: 'khamis-mushait', label: 'Khamis Mushait' },
      { value: 'hail', label: 'Hail' },
      { value: 'hafar-al-batin', label: 'Hafar Al Batin' },
      { value: 'al-mubarraz', label: 'Al Mubarraz' },
      { value: 'al-kharj', label: 'Al Kharj' },
      { value: 'al-hufuf', label: 'Al Hufuf' },
      { value: 'al-mubarraz', label: 'Al Mubarraz' },
      { value: 'najran', label: 'Najran' },
      { value: 'al-jubail', label: 'Al Jubail' },
      { value: 'yanbu', label: 'Yanbu' },
      { value: 'al-qatif', label: 'Al Qatif' },
      { value: 'arar', label: 'Arar' },
      { value: 'sakaka', label: 'Sakaka' },
      { value: 'jizan', label: 'Jizan' },
      { value: 'qurayyat', label: 'Qurayyat' },
      { value: 'dhahran', label: 'Dhahran' },
      { value: 'al-bahah', label: 'Al Bahah' },
      { value: 'tarut', label: 'Tarut' },
      { value: 'qatif', label: 'Qatif' },
      { value: 'al-hawiyah', label: 'Al Hawiyah' },
      { value: 'unaizah', label: 'Unaizah' },
      { value: 'rafha', label: 'Rafha' },
      { value: 'turubah', label: 'Turubah' },
      { value: 'al-khobar', label: 'Al Khobar' },
      { value: 'al-qunfudhah', label: 'Al Qunfudhah' },
      { value: 'al-zulfi', label: 'Al Zulfi' },
      { value: 'sharurah', label: 'Sharurah' },
      { value: 'samitah', label: 'Samitah' },
      { value: 'al-bad', label: 'Al Bad' },
      { value: 'al-wajh', label: 'Al Wajh' },
      { value: 'duba', label: 'Duba' },
      { value: 'tabuk', label: 'Tabuk' },
      { value: 'al-bukayriyah', label: 'Al Bukayriyah' },
      { value: 'al-majmaah', label: 'Al Majmaah' },
      { value: 'al-zulfi', label: 'Al Zulfi' },
      { value: 'al-kharj', label: 'Al Kharj' },
      { value: 'al-hofuf', label: 'Al Hofuf' },
      { value: 'al-mubarraz', label: 'Al Mubarraz' },
      { value: 'al-hasa', label: 'Al Hasa' },
      { value: 'al-ahsa', label: 'Al Ahsa' },
    ],
  },
  { value: 'sn', label: 'Senegal', code: 'SN', cities: [] },
  { value: 'rs', label: 'Serbia', code: 'RS', cities: [] },
  { value: 'sc', label: 'Seychelles', code: 'SC', cities: [] },
  { value: 'sl', label: 'Sierra Leone', code: 'SL', cities: [] },
  {
    value: 'sg',
    label: 'Singapore',
    code: 'SG',
    cities: [
      { value: 'singapore', label: 'Singapore' },
    ],
  },
  { value: 'sk', label: 'Slovakia', code: 'SK', cities: [] },
  { value: 'si', label: 'Slovenia', code: 'SI', cities: [] },
  { value: 'sb', label: 'Solomon Islands', code: 'SB', cities: [] },
  { value: 'so', label: 'Somalia', code: 'SO', cities: [] },
  {
    value: 'za',
    label: 'South Africa',
    code: 'ZA',
    cities: [
      { value: 'johannesburg', label: 'Johannesburg' },
      { value: 'cape-town', label: 'Cape Town' },
      { value: 'durban', label: 'Durban' },
      { value: 'pretoria', label: 'Pretoria' },
      { value: 'port-elizabeth', label: 'Port Elizabeth' },
      { value: 'pietermaritzburg', label: 'Pietermaritzburg' },
      { value: 'bloemfontein', label: 'Bloemfontein' },
      { value: 'east-london', label: 'East London' },
    ],
  },
  { value: 'ss', label: 'South Sudan', code: 'SS', cities: [] },
  {
    value: 'es',
    label: 'Spain',
    code: 'ES',
    cities: [
      { value: 'madrid', label: 'Madrid' },
      { value: 'barcelona', label: 'Barcelona' },
      { value: 'valencia', label: 'Valencia' },
      { value: 'seville', label: 'Seville' },
      { value: 'zaragoza', label: 'Zaragoza' },
      { value: 'malaga', label: 'Málaga' },
      { value: 'murcia', label: 'Murcia' },
      { value: 'palma', label: 'Palma' },
      { value: 'las-palmas', label: 'Las Palmas' },
      { value: 'bilbao', label: 'Bilbao' },
    ],
  },
  { value: 'lk', label: 'Sri Lanka', code: 'LK', cities: [] },
  { value: 'sd', label: 'Sudan', code: 'SD', cities: [] },
  { value: 'sr', label: 'Suriname', code: 'SR', cities: [] },
  { value: 'se', label: 'Sweden', code: 'SE', cities: [] },
  { value: 'ch', label: 'Switzerland', code: 'CH', cities: [] },
  { value: 'sy', label: 'Syria', code: 'SY', cities: [] },
  
  // T
  { value: 'tw', label: 'Taiwan', code: 'TW', cities: [] },
  { value: 'tj', label: 'Tajikistan', code: 'TJ', cities: [] },
  { value: 'tz', label: 'Tanzania', code: 'TZ', cities: [] },
  {
    value: 'th',
    label: 'Thailand',
    code: 'TH',
    cities: [
      { value: 'bangkok', label: 'Bangkok' },
      { value: 'chiang-mai', label: 'Chiang Mai' },
      { value: 'phuket', label: 'Phuket' },
      { value: 'pattaya', label: 'Pattaya' },
      { value: 'hat-yai', label: 'Hat Yai' },
      { value: 'nakhon-ratchasima', label: 'Nakhon Ratchasima' },
      { value: 'udon-thani', label: 'Udon Thani' },
      { value: 'khon-kaen', label: 'Khon Kaen' },
    ],
  },
  { value: 'tl', label: 'Timor-Leste', code: 'TL', cities: [] },
  { value: 'tg', label: 'Togo', code: 'TG', cities: [] },
  { value: 'to', label: 'Tonga', code: 'TO', cities: [] },
  { value: 'tt', label: 'Trinidad and Tobago', code: 'TT', cities: [] },
  { value: 'tn', label: 'Tunisia', code: 'TN', cities: [] },
  {
    value: 'tr',
    label: 'Turkey',
    code: 'TR',
    cities: [
      { value: 'istanbul', label: 'Istanbul' },
      { value: 'ankara', label: 'Ankara' },
      { value: 'izmir', label: 'İzmir' },
      { value: 'bursa', label: 'Bursa' },
      { value: 'antalya', label: 'Antalya' },
      { value: 'konya', label: 'Konya' },
      { value: 'adana', label: 'Adana' },
      { value: 'gaziantep', label: 'Gaziantep' },
    ],
  },
  { value: 'tm', label: 'Turkmenistan', code: 'TM', cities: [] },
  { value: 'tv', label: 'Tuvalu', code: 'TV', cities: [] },
  
  // U
  { value: 'ug', label: 'Uganda', code: 'UG', cities: [] },
  { value: 'ua', label: 'Ukraine', code: 'UA', cities: [] },
  {
    value: 'ae',
    label: 'United Arab Emirates',
    code: 'AE',
    cities: [
      { value: 'dubai', label: 'Dubai' },
      { value: 'abu-dhabi', label: 'Abu Dhabi' },
      { value: 'sharjah', label: 'Sharjah' },
      { value: 'al-ain', label: 'Al Ain' },
      { value: 'ajman', label: 'Ajman' },
      { value: 'ras-al-khaimah', label: 'Ras Al Khaimah' },
      { value: 'fujairah', label: 'Fujairah' },
      { value: 'umm-al-quwain', label: 'Umm Al Quwain' },
      { value: 'khor-fakkan', label: 'Khor Fakkan' },
      { value: 'kalba', label: 'Kalba' },
      { value: 'dibba', label: 'Dibba' },
      { value: 'jebel-ali', label: 'Jebel Ali' },
      { value: 'al-dhafra', label: 'Al Dhafra' },
      { value: 'madinat-zayed', label: 'Madinat Zayed' },
      { value: 'ruwais', label: 'Ruwais' },
      { value: 'ghantoot', label: 'Ghantoot' },
      { value: 'liwa-oasis', label: 'Liwa Oasis' },
      { value: 'dhaid', label: 'Dhaid' },
      { value: 'masafi', label: 'Masafi' },
      { value: 'dibba-al-hisn', label: 'Dibba Al Hisn' },
      { value: 'khor-kalba', label: 'Khor Kalba' },
      { value: 'al-madam', label: 'Al Madam' },
      { value: 'al-dhaid', label: 'Al Dhaid' },
      { value: 'al-bataeh', label: 'Al Bataeh' },
      { value: 'al-ramla', label: 'Al Ramla' },
      { value: 'al-hamriyah', label: 'Al Hamriyah' },
      { value: 'al-ghail', label: 'Al Ghail' },
      { value: 'al-madam', label: 'Al Madam' },
      { value: 'al-shamkhah', label: 'Al Shamkhah' },
      { value: 'al-mirfa', label: 'Al Mirfa' },
      { value: 'al-sila', label: 'Al Sila' },
      { value: 'delma-island', label: 'Delma Island' },
      { value: 'sir-bani-yas', label: 'Sir Bani Yas' },
      { value: 'marawah-island', label: 'Marawah Island' },
      { value: 'yas-island', label: 'Yas Island' },
      { value: 'saadiyat-island', label: 'Saadiyat Island' },
      { value: 'al-reem-island', label: 'Al Reem Island' },
      { value: 'palm-jumeirah', label: 'Palm Jumeirah' },
      { value: 'palm-deira', label: 'Palm Deira' },
      { value: 'palm-jebel-ali', label: 'Palm Jebel Ali' },
      { value: 'world-islands', label: 'World Islands' },
      { value: 'the-world', label: 'The World' },
    ],
  },
  {
    value: 'uk',
    label: 'United Kingdom',
    code: 'GB',
    cities: [
      { value: 'london', label: 'London' },
      { value: 'manchester', label: 'Manchester' },
      { value: 'birmingham', label: 'Birmingham' },
      { value: 'glasgow', label: 'Glasgow' },
      { value: 'liverpool', label: 'Liverpool' },
      { value: 'leeds', label: 'Leeds' },
      { value: 'edinburgh', label: 'Edinburgh' },
      { value: 'bristol', label: 'Bristol' },
      { value: 'sheffield', label: 'Sheffield' },
      { value: 'cardiff', label: 'Cardiff' },
      { value: 'leicester', label: 'Leicester' },
      { value: 'coventry', label: 'Coventry' },
      { value: 'belfast', label: 'Belfast' },
      { value: 'nottingham', label: 'Nottingham' },
      { value: 'kingston-upon-hull', label: 'Kingston upon Hull' },
      { value: 'newcastle-upon-tyne', label: 'Newcastle upon Tyne' },
      { value: 'southampton', label: 'Southampton' },
      { value: 'derby', label: 'Derby' },
      { value: 'portsmouth', label: 'Portsmouth' },
      { value: 'brighton', label: 'Brighton' },
      { value: 'reading', label: 'Reading' },
      { value: 'northampton', label: 'Northampton' },
      { value: 'luton', label: 'Luton' },
      { value: 'bolton', label: 'Bolton' },
      { value: 'swansea', label: 'Swansea' },
      { value: 'swindon', label: 'Swindon' },
      { value: 'southend-on-sea', label: 'Southend-on-Sea' },
      { value: 'middlesbrough', label: 'Middlesbrough' },
      { value: 'peterborough', label: 'Peterborough' },
      { value: 'cambridge', label: 'Cambridge' },
      { value: 'oxford', label: 'Oxford' },
      { value: 'norwich', label: 'Norwich' },
      { value: 'york', label: 'York' },
      { value: 'ipswich', label: 'Ipswich' },
      { value: 'bournemouth', label: 'Bournemouth' },
      { value: 'plymouth', label: 'Plymouth' },
      { value: 'blackpool', label: 'Blackpool' },
      { value: 'wigan', label: 'Wigan' },
      { value: 'burnley', label: 'Burnley' },
      { value: 'huddersfield', label: 'Huddersfield' },
      { value: 'rotherham', label: 'Rotherham' },
      { value: 'preston', label: 'Preston' },
      { value: 'sunderland', label: 'Sunderland' },
      { value: 'stoke-on-trent', label: 'Stoke-on-Trent' },
      { value: 'wolverhampton', label: 'Wolverhampton' },
      { value: 'blackburn', label: 'Blackburn' },
      { value: 'oldham', label: 'Oldham' },
      { value: 'stockport', label: 'Stockport' },
    ],
  },
  {
    value: 'us',
    label: 'United States of America',
    code: 'US',
    cities: [
      { value: 'new-york', label: 'New York' },
      { value: 'los-angeles', label: 'Los Angeles' },
      { value: 'chicago', label: 'Chicago' },
      { value: 'houston', label: 'Houston' },
      { value: 'phoenix', label: 'Phoenix' },
      { value: 'philadelphia', label: 'Philadelphia' },
      { value: 'san-antonio', label: 'San Antonio' },
      { value: 'san-diego', label: 'San Diego' },
      { value: 'dallas', label: 'Dallas' },
      { value: 'san-jose', label: 'San Jose' },
      { value: 'austin', label: 'Austin' },
      { value: 'jacksonville', label: 'Jacksonville' },
      { value: 'fort-worth', label: 'Fort Worth' },
      { value: 'columbus', label: 'Columbus' },
      { value: 'charlotte', label: 'Charlotte' },
      { value: 'san-francisco', label: 'San Francisco' },
      { value: 'indianapolis', label: 'Indianapolis' },
      { value: 'seattle', label: 'Seattle' },
      { value: 'denver', label: 'Denver' },
      { value: 'washington', label: 'Washington' },
      { value: 'boston', label: 'Boston' },
      { value: 'el-paso', label: 'El Paso' },
      { value: 'nashville', label: 'Nashville' },
      { value: 'detroit', label: 'Detroit' },
      { value: 'oklahoma-city', label: 'Oklahoma City' },
      { value: 'portland', label: 'Portland' },
      { value: 'las-vegas', label: 'Las Vegas' },
      { value: 'memphis', label: 'Memphis' },
      { value: 'louisville', label: 'Louisville' },
      { value: 'baltimore', label: 'Baltimore' },
      { value: 'milwaukee', label: 'Milwaukee' },
      { value: 'albuquerque', label: 'Albuquerque' },
      { value: 'tucson', label: 'Tucson' },
      { value: 'fresno', label: 'Fresno' },
      { value: 'sacramento', label: 'Sacramento' },
      { value: 'kansas-city', label: 'Kansas City' },
      { value: 'mesa', label: 'Mesa' },
      { value: 'atlanta', label: 'Atlanta' },
      { value: 'omaha', label: 'Omaha' },
      { value: 'colorado-springs', label: 'Colorado Springs' },
      { value: 'raleigh', label: 'Raleigh' },
      { value: 'virginia-beach', label: 'Virginia Beach' },
      { value: 'miami', label: 'Miami' },
      { value: 'oakland', label: 'Oakland' },
      { value: 'minneapolis', label: 'Minneapolis' },
      { value: 'tulsa', label: 'Tulsa' },
      { value: 'cleveland', label: 'Cleveland' },
      { value: 'wichita', label: 'Wichita' },
      { value: 'arlington', label: 'Arlington' },
      { value: 'tampa', label: 'Tampa' },
      { value: 'new-orleans', label: 'New Orleans' },
      { value: 'honolulu', label: 'Honolulu' },
      { value: 'anaheim', label: 'Anaheim' },
      { value: 'santa-ana', label: 'Santa Ana' },
      { value: 'st-louis', label: 'St. Louis' },
      { value: 'corpus-christi', label: 'Corpus Christi' },
      { value: 'riverside', label: 'Riverside' },
      { value: 'lexington', label: 'Lexington' },
      { value: 'pittsburgh', label: 'Pittsburgh' },
      { value: 'anchorage', label: 'Anchorage' },
      { value: 'stockton', label: 'Stockton' },
      { value: 'cincinnati', label: 'Cincinnati' },
      { value: 'st-paul', label: 'St. Paul' },
      { value: 'toledo', label: 'Toledo' },
      { value: 'greensboro', label: 'Greensboro' },
      { value: 'newark', label: 'Newark' },
      { value: 'buffalo', label: 'Buffalo' },
      { value: 'plano', label: 'Plano' },
      { value: 'lincoln', label: 'Lincoln' },
      { value: 'henderson', label: 'Henderson' },
      { value: 'fort-wayne', label: 'Fort Wayne' },
      { value: 'jersey-city', label: 'Jersey City' },
      { value: 'st-petersburg', label: 'St. Petersburg' },
      { value: 'chula-vista', label: 'Chula Vista' },
      { value: 'norfolk', label: 'Norfolk' },
      { value: 'orlando', label: 'Orlando' },
      { value: 'chandler', label: 'Chandler' },
      { value: 'laredo', label: 'Laredo' },
      { value: 'madison', label: 'Madison' },
      { value: 'durham', label: 'Durham' },
      { value: 'lubbock', label: 'Lubbock' },
      { value: 'winston-salem', label: 'Winston-Salem' },
      { value: 'garland', label: 'Garland' },
      { value: 'glendale', label: 'Glendale' },
      { value: 'hialeah', label: 'Hialeah' },
      { value: 'reno', label: 'Reno' },
      { value: 'baton-rouge', label: 'Baton Rouge' },
      { value: 'irvine', label: 'Irvine' },
      { value: 'chesapeake', label: 'Chesapeake' },
      { value: 'irving', label: 'Irving' },
      { value: 'scottsdale', label: 'Scottsdale' },
      { value: 'north-las-vegas', label: 'North Las Vegas' },
      { value: 'fremont', label: 'Fremont' },
      { value: 'boise', label: 'Boise' },
      { value: 'richmond', label: 'Richmond' },
    ],
  },
  { value: 'uy', label: 'Uruguay', code: 'UY', cities: [] },
  { value: 'uz', label: 'Uzbekistan', code: 'UZ', cities: [] },
  
  // V
  { value: 'vu', label: 'Vanuatu', code: 'VU', cities: [] },
  { value: 'va', label: 'Vatican City', code: 'VA', cities: [] },
  { value: 've', label: 'Venezuela', code: 'VE', cities: [] },
  {
    value: 'vn',
    label: 'Vietnam',
    code: 'VN',
    cities: [
      { value: 'ho-chi-minh', label: 'Ho Chi Minh City' },
      { value: 'hanoi', label: 'Hanoi' },
      { value: 'da-nang', label: 'Da Nang' },
      { value: 'haiphong', label: 'Haiphong' },
      { value: 'can-tho', label: 'Can Tho' },
      { value: 'nha-trang', label: 'Nha Trang' },
      { value: 'hue', label: 'Hue' },
      { value: 'vung-tau', label: 'Vung Tau' },
    ],
  },
  
  // Y
  { value: 'ye', label: 'Yemen', code: 'YE', cities: [] },
  
  // Z
  { value: 'zm', label: 'Zambia', code: 'ZM', cities: [] },
  { value: 'zw', label: 'Zimbabwe', code: 'ZW', cities: [] },
]

// Get cities for a country - sorted alphabetically
export function getCitiesForCountry(countryValue: string): City[] {
  const country = countries.find(c => c.value === countryValue)
  const cities = country?.cities || []
  // Sort cities alphabetically by label
  return [...cities].sort((a, b) => a.label.localeCompare(b.label))
}

// Get all countries as options for select - sorted alphabetically
export function getCountryOptions() {
  const options = countries.map(c => ({ value: c.value, label: c.label }))
  // Sort countries alphabetically by label
  return [...options].sort((a, b) => a.label.localeCompare(b.label))
}

// Get country by value
export function getCountryByValue(countryValue: string): Country | undefined {
  return countries.find(c => c.value === countryValue)
}

// Search countries by name (for future search functionality)
export function searchCountries(query: string) {
  const lowerQuery = query.toLowerCase()
  return countries.filter(c => 
    c.label.toLowerCase().includes(lowerQuery) ||
    c.code.toLowerCase().includes(lowerQuery)
  )
}
